export interface TypeEntry {
  name: string;
  detail: string;
}

/** The %Library data types and base/framework classes that show up after `As ` in a Property,
 * Parameter, or method return-type declaration — not exhaustive (IRIS ships hundreds of classes),
 * but covers what actually gets typed by hand day to day. */
export const DATA_TYPES: TypeEntry[] = [
  { name: "%String", detail: "texto" },
  { name: "%Boolean", detail: "0 ou 1" },
  { name: "%Integer", detail: "inteiro" },
  { name: "%SmallInt", detail: "inteiro pequeno" },
  { name: "%TinyInt", detail: "inteiro muito pequeno" },
  { name: "%BigInt", detail: "inteiro grande" },
  { name: "%Numeric", detail: "número decimal" },
  { name: "%Double", detail: "ponto flutuante" },
  { name: "%Float", detail: "ponto flutuante" },
  { name: "%Decimal", detail: "decimal de precisão fixa" },
  { name: "%Currency", detail: "valor monetário" },
  { name: "%Date", detail: "data" },
  { name: "%Time", detail: "hora" },
  { name: "%TimeStamp", detail: "data e hora" },
  { name: "%PosixTime", detail: "timestamp POSIX" },
  { name: "%Binary", detail: "dados binários" },
  { name: "%Char", detail: "caractere único" },
  { name: "%VarString", detail: "texto de tamanho variável" },
  { name: "%Status", detail: "código de status/erro do sistema" },
  { name: "%List", detail: "$list (estrutura nativa)" },
  { name: "%ListOfDataTypes", detail: "coleção de valores simples" },
  { name: "%ListOfObjects", detail: "coleção de objetos" },
  { name: "%ArrayOfDataTypes", detail: "array chave/valor de valores simples" },
  { name: "%ArrayOfObjects", detail: "array chave/valor de objetos" },
  { name: "%RegisteredObject", detail: "classe base — objeto não persistente" },
  { name: "%Persistent", detail: "classe base — objeto persistido no banco" },
  { name: "%SerialObject", detail: "classe base — objeto embutido/serial" },
  { name: "%CSP.Page", detail: "página CSP clássica" },
  { name: "%CSP.REST", detail: "endpoint REST" },
  { name: "%CSP.Request", detail: "objeto de requisição CSP (%request)" },
  { name: "%CSP.Response", detail: "objeto de resposta CSP (%response)" },
  { name: "%CSP.Session", detail: "sessão CSP (%session)" },
  { name: "%SOAP.WebService", detail: "web service SOAP" },
  { name: "%XML.Adaptor", detail: "serialização XML" },
  { name: "%DynamicObject", detail: "objeto JSON dinâmico {}" },
  { name: "%DynamicArray", detail: "array JSON dinâmico []" },
  { name: "%Net.HttpRequest", detail: "cliente HTTP" },
  { name: "%Net.HttpResponse", detail: "resposta HTTP" },
  { name: "%SQL.Statement", detail: "statement SQL preparado" },
  { name: "%ResultSet", detail: "resultado de query" },
  { name: "%Stream.GlobalCharacter", detail: "stream de texto em globals" },
  { name: "%Stream.GlobalBinary", detail: "stream binário em globals" },
  { name: "%Stream.FileCharacter", detail: "stream de texto em arquivo" },
  { name: "%Stream.FileBinary", detail: "stream binário em arquivo" },
  { name: "%Stream.Object", detail: "classe base de stream" },
  { name: "%Library.Populate", detail: "geração de dados de teste" },
  { name: "Ens.BusinessService", detail: "serviço de negócio (Interoperability)" },
  { name: "Ens.BusinessOperation", detail: "operação de negócio (Interoperability)" },
  { name: "Ens.BusinessProcessBPL", detail: "processo de negócio BPL (Interoperability)" },
  { name: "Ens.Request", detail: "mensagem de request (Interoperability)" },
  { name: "Ens.Response", detail: "mensagem de response (Interoperability)" },
];

/** Common `$SYSTEM.X` utility classes — real classes under the hood (`%SYSTEM.X`), so once one is
 * picked, member completion for it reuses the normal class-member lookup (see classMembers.ts). */
export const SYSTEM_CLASSES: TypeEntry[] = [
  { name: "Util", detail: "$SYSTEM.Util — utilidades gerais do sistema" },
  { name: "Security", detail: "$SYSTEM.Security — usuários, roles, permissões" },
  { name: "SQL", detail: "$SYSTEM.SQL — utilidades SQL" },
  { name: "Process", detail: "$SYSTEM.Process — processo atual" },
  { name: "Version", detail: "$SYSTEM.Version — versão do IRIS/Caché" },
  { name: "OBJ", detail: "$SYSTEM.OBJ — compilação/exportação de classes" },
  { name: "CLS", detail: "$SYSTEM.CLS — utilidades de classe" },
  { name: "Encryption", detail: "$SYSTEM.Encryption — criptografia" },
  { name: "License", detail: "$SYSTEM.License — licenciamento" },
  { name: "WorkMgr", detail: "$SYSTEM.WorkMgr — gerenciador de work queues" },
  { name: "Diagnostics", detail: "$SYSTEM.Diagnostics" },
  { name: "Event", detail: "$SYSTEM.Event — log de eventos" },
  { name: "Status", detail: "$SYSTEM.Status — manipulação de %Status" },
  { name: "Util2", detail: "$SYSTEM.Util2" },
  { name: "INetInfo", detail: "$SYSTEM.INetInfo — informações de rede" },
];
